### PR TITLE
chore(github action): ignore version for tj-actions/changed-files in sync files

### PR DESCRIPTION
**Pull request by hsgwa**
Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>

This PR fixes conflicts between sync-files and dependabot

- https://github.com/tier4/CARET_trace/pull/71
- https://github.com/tier4/CARET_trace/pull/67

### CODE REVIEW

**Review by keita1523 — APPROVED** [review]
LGTM.
I checked this regex extracted the version described after `tj-actions/changed-files@`.

**Comment by takam5f2** [comment]
@hsgwa  
I'm sorry for waiting for a long time. Let me confirm your intention.
Do you want to use the version recommended by `pre-commit.ci` rather than recommended by Autoware Foundation?

**Comment by hsgwa** [comment]
@takam5f2 
Yes. There are several ways to fix conflict, but that is what I intend to do.
> Do you want to use the version recommended by pre-commit.ci rather than recommended by Autoware Foundation?

**Review by takam5f2 — APPROVED** [review]
LGTM

**Pull request merged**
