### PR TITLE
ci: replace ament_lint_common with pre-commit and caret_lint_common

### PR DESCRIPTION
**Pull request by kenji-miyake**
In order to pass CI with both Galactic and Humble.

### CODE REVIEW

**Comment by hsgwa** [comment]
@takam5f2 

An error occurred in caret setup as well.

```
sudo docker run -it --rm --name caret_test ros:galactic
adduser autoware
apt update && apt install -y vim
adduser autoware sudo
su - autoware
$ cd
$ git clone https://github.com/tier4/caret.git ros2_caret
$ cd ros2_caret
$ mkdir src
$ vcs import src < caret.repos --recursive
$ cd src/CARET/CARET_trace
$ git checkout -b replace-ament-uncrustify-with-clang-format origin/replace-ament-uncrustify-with-clang-format
$ cd ~/ros2_caret
$ ./setup_caret.sh
TASK [caret : caret (rosdep install dependencies)] *********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "rosdep install -y --from-paths src --ignore-src --rosdistro galactic -y --skip-keys \"console_bridge fastcdr fastrtps rti-connext-dds-5.3.1 urdfdom_headers\"\n", "delta": "0:00:04.236494", "end": "2022-08-29 14:33:28.437494", "msg": "non-zero return code", "rc": 1, "start": "2022-08-29 14:33:24.201000", "stderr": "ERROR: the following packages/stacks could not have their rosdep keys resolved\nto system dependencies:\ncaret_trace: Cannot locate rosdep definition for [autoware_lint_common]", "stderr_lines": ["ERROR: the following packages/stacks could not have their rosdep keys resolved", "to system dependencies:", "caret_trace: Cannot locate rosdep definition for [autoware_lint_common]"], "stdout": "", "stdout_lines": []}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=18   changed=13   unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

Failed.

$ # source /opt/ros/galactic/setup.bash
$
```

**Comment by takam5f2** [comment]
@hsgwa  
Could you try the following PR?
https://github.com/tier4/caret/pull/27

**Review by hsgwa — APPROVED** [review]
LGTM!

**Comment by hsgwa** [comment]
@takam5f2 (cc: @kenji-miyake )

Just a consultation.
`chore: sync files PR` is trying to sync " (https://github.com/tier4/CARET_trace/pull/45) autoware-foundation's .pre-commit-config.yaml" and other changes
.
Though I'd like to sync modifications except for`.pre-commit-config.yaml`, because this PR modification will be removed.

I'm thinking a option to solve:
1. change sync `.pre-commit-config.yaml` from autoware-founcation to caret-common
2. modify manually `.pre-commit-config.yaml` in caret-common.

Are there any issues or better solutions?

**Comment by kenji-miyake** [comment]
I think either option is fine.
Or seeing the diff of https://github.com/tier4/CARET_trace/pull/45, syncing from `autoware_common` also works.

**Comment by hsgwa** [comment]
@kenji-miyake 

Thank you for your comment!
autoware_common looks good :100: 

After consulting with @takam5f2, I'll change sync source from `autoware-foundation` to `autoware_common`.

**Pull request merged**
